package static

// EventHandler is a function that will handle Event's generated by the Build process.
type EventHandler func(event Event)

// defaultEventHandler does nothing with the event.
var defaultEventHandler = func(event Event) {}
